#!/bin/bash

# The default packages that I use nearly everywhere
PKGS="numpy scipy matplotlib"
DOCS="sphinx sphinx_rtd_theme sphinx-autobuild"
REPLS="jupyter ptpython"
TESTS="pytest hypothesis"
DEFAULT_PKGS="$DOCS $REPLS $TESTS $PKGS"

usage () {
    echo "Usage: pyenv <command> ..."
    echo
    echo "Commands:"
    echo -e "\tnew:\tCreate a new virtual environment"
}

new () {

    python -m venv env
    source env/bin/activate

    pip install $DEFAULT_PKGS

    if [[ -f "requirements.txt" ]] ; then
        echo "Requirements file detected"
        pip install -r requirements.txt
    fi

    deactivate
}

case $1 in

    "new")
        new;;

    *)
        usage
esac
